server:
  port: 9000
spring:
  application:
    name: gateway

#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka
#自定义路由映射
zuul:
  routes:
    consumer-service: /apigateway/consumer/**
    productor-service: /apigateway/productor/**
  #不对外暴露的服务，注意ignored-services与routes同级
  #  ignored-services: consumer-service
  ignored-patterns: /**-service/**
