server:
  port: 8762
#服务名称
spring:
  application:
    name: consumer-service
  #zipkin服务地址
  zipkin:
    base-url: http://localhost:9411/
  #sleuth采样百分比，开发环境可以是1，表示全部，生产环境就用默认1%
  sleuth:
    sampler:
      probability: 1
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka


#自定义负载均衡策略
productor-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflx.loadbalancer.RandomRule

#修改feign调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

#暴露全部信息
management:
  endpoint:
    web:
      exposure:
        include: "*"